name: dayasagar_praise_worship
description: A beautiful praise and worship app for Dayasagar community
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '^3.8.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3
  firebase_storage: ^11.6.0

  flutter_riverpod: ^2.4.9

  go_router: ^12.1.3

  shared_preferences: ^2.2.2

  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2

  material_design_icons_flutter: ^7.0.7296
  google_fonts: ^6.1.0

  image_picker: ^1.0.4

  http: ^1.1.0
  rename_app: ^1.6.1
  url_launcher: ^6.2.2
  share_plus: ^7.2.2

  crypto: ^3.0.3

  intl: ^0.19.0
  path_provider: ^2.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  firebase_auth_mocks: ^0.13.0
  fake_cloud_firestore: ^2.4.1+1
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/bible/EN-English/asv.json
    - assets/bible/OD-Odia/asv.json
    - assets/bible/HI-Hindi/asv.json
    - assets/images/logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/1024.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/1024.png"
  min_sdk_android: 21
  # Play Store icon (optional)
  play_store_config:
    image_path: "assets/images/play_store_512.png"
